/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Customerbilling;

import javax.swing.JFrame;
import java.util.Calendar;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;



/**
 *
 * @author patil
 */
public class Customer_billing extends javax.swing.JFrame {

    String iTax, iSubTotal, iTotal;
    double[] itemcost = new double[20];
    
    
    public Customer_billing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtxtcustomerref = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtfirstname = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jtxtmobileno = new javax.swing.JTextField();
        jtxtlastname = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jchkespresso = new javax.swing.JCheckBox();
        jchkicedcoffee = new javax.swing.JCheckBox();
        jchkmacchiato = new javax.swing.JCheckBox();
        jchkcwc = new javax.swing.JCheckBox();
        jchkhouseb = new javax.swing.JCheckBox();
        jchklatte = new javax.swing.JCheckBox();
        jchkdecaf = new javax.swing.JCheckBox();
        jchklblack = new javax.swing.JCheckBox();
        jchkcc = new javax.swing.JCheckBox();
        jchkicedf = new javax.swing.JCheckBox();
        jtxtcwc = new javax.swing.JTextField();
        jtxticedf = new javax.swing.JTextField();
        jtxtmacchiato = new javax.swing.JTextField();
        jtxticedcoffee = new javax.swing.JTextField();
        jtxtespresso = new javax.swing.JTextField();
        jtxtcc = new javax.swing.JTextField();
        jtxtlblack = new javax.swing.JTextField();
        jtxthouseb = new javax.swing.JTextField();
        jtxtdecaf = new javax.swing.JTextField();
        jtxtlatte = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jchkb1 = new javax.swing.JCheckBox();
        jchkb3 = new javax.swing.JCheckBox();
        jchkb5 = new javax.swing.JCheckBox();
        jchkb2 = new javax.swing.JCheckBox();
        jchkb6 = new javax.swing.JCheckBox();
        jchkb4 = new javax.swing.JCheckBox();
        jchkb7 = new javax.swing.JCheckBox();
        jtxtb7 = new javax.swing.JTextField();
        jtxtb1 = new javax.swing.JTextField();
        jtxtb2 = new javax.swing.JTextField();
        jtxtb3 = new javax.swing.JTextField();
        jtxtb4 = new javax.swing.JTextField();
        jtxtb5 = new javax.swing.JTextField();
        jtxtb6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxttotal = new javax.swing.JTextField();
        jtxttax = new javax.swing.JTextField();
        jtxtsubtotal = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtxtreceipt = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1300, 630));
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(15, 15, 15, 15, new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel1.setText("Customer ref:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 140, 30));

        jtxtcustomerref.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jtxtcustomerref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcustomerrefActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtcustomerref, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, 140, 30));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("First Name:");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 130, 30));

        jtxtfirstname.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jtxtfirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtfirstnameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtfirstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 80, 140, 30));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Last Name:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 80, 120, 30));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel4.setText("Mobile Number:");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 80, 160, -1));

        jtxtmobileno.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jPanel2.add(jtxtmobileno, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 80, 160, 30));

        jtxtlastname.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jtxtlastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtlastnameActionPerformed(evt);
            }
        });
        jPanel2.add(jtxtlastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 130, 30));

        jButton4.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 30, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 1030, 140));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(204, 204, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Brush Script MT", 0, 32)); // NOI18N
        jLabel6.setText("Coffee Drinks");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 170, -1));

        jchkespresso.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkespresso.setText("Espresso");
        jchkespresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkespressoActionPerformed(evt);
            }
        });
        jPanel6.add(jchkespresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 110, 30));

        jchkicedcoffee.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkicedcoffee.setText("Iced Coffee");
        jchkicedcoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkicedcoffeeActionPerformed(evt);
            }
        });
        jPanel6.add(jchkicedcoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jchkmacchiato.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkmacchiato.setText("Macchiato");
        jchkmacchiato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkmacchiatoActionPerformed(evt);
            }
        });
        jPanel6.add(jchkmacchiato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jchkcwc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkcwc.setText("Coffee With Cream");
        jchkcwc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkcwcActionPerformed(evt);
            }
        });
        jPanel6.add(jchkcwc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jchkhouseb.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkhouseb.setText("House Blend");
        jchkhouseb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkhousebActionPerformed(evt);
            }
        });
        jPanel6.add(jchkhouseb, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jchklatte.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchklatte.setText("Latte");
        jchklatte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchklatteActionPerformed(evt);
            }
        });
        jPanel6.add(jchklatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, -1, -1));

        jchkdecaf.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkdecaf.setText("Decaf Coffee");
        jchkdecaf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkdecafActionPerformed(evt);
            }
        });
        jPanel6.add(jchkdecaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, -1, -1));

        jchklblack.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchklblack.setText("Long Black");
        jchklblack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchklblackActionPerformed(evt);
            }
        });
        jPanel6.add(jchklblack, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jchkcc.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkcc.setText("Chocalate Coffee");
        jchkcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkccActionPerformed(evt);
            }
        });
        jPanel6.add(jchkcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jchkicedf.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkicedf.setText("Iced Frappe");
        jchkicedf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkicedfActionPerformed(evt);
            }
        });
        jPanel6.add(jchkicedf, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, -1, -1));

        jtxtcwc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtcwc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcwc.setText("0");
        jtxtcwc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtcwcActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtcwc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 80, 30));

        jtxticedf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxticedf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxticedf.setText("0");
        jPanel6.add(jtxticedf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 420, 80, 30));

        jtxtmacchiato.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtmacchiato.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtmacchiato.setText("0");
        jPanel6.add(jtxtmacchiato, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 140, 80, 30));

        jtxticedcoffee.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxticedcoffee.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxticedcoffee.setText("0");
        jPanel6.add(jtxticedcoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 80, 30));

        jtxtespresso.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtespresso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtespresso.setText("0");
        jtxtespresso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtespressoActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtespresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 60, 80, 30));

        jtxtcc.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtcc.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtcc.setText("0");
        jPanel6.add(jtxtcc, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 80, 30));

        jtxtlblack.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtlblack.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlblack.setText("0");
        jPanel6.add(jtxtlblack, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 80, 30));

        jtxthouseb.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxthouseb.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxthouseb.setText("0");
        jPanel6.add(jtxthouseb, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 300, 80, 30));

        jtxtdecaf.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtdecaf.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtdecaf.setText("0");
        jPanel6.add(jtxtdecaf, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 80, 30));

        jtxtlatte.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtlatte.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtlatte.setText("0");
        jPanel6.add(jtxtlatte, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, 80, 30));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 460));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 360, 500));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(204, 204, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Brush Script MT", 0, 32)); // NOI18N
        jLabel7.setText("Breakfast");
        jPanel7.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 130, -1));

        jchkb1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkb1.setText("Spanish Omelette");
        jchkb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkb1ActionPerformed(evt);
            }
        });
        jPanel7.add(jchkb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        jchkb3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkb3.setText("Nutella French Toast");
        jchkb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkb3ActionPerformed(evt);
            }
        });
        jPanel7.add(jchkb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        jchkb5.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkb5.setText("Waffle Attack");
        jchkb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkb5ActionPerformed(evt);
            }
        });
        jPanel7.add(jchkb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jchkb2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkb2.setText("Eggs Benedict");
        jchkb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkb2ActionPerformed(evt);
            }
        });
        jPanel7.add(jchkb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        jchkb6.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkb6.setText("English Breakfast");
        jchkb6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkb6ActionPerformed(evt);
            }
        });
        jPanel7.add(jchkb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, -1, -1));

        jchkb4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkb4.setText("S'mores Crepes");
        jchkb4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkb4ActionPerformed(evt);
            }
        });
        jPanel7.add(jchkb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jchkb7.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jchkb7.setText("Granola + Yogurt");
        jchkb7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jchkb7ActionPerformed(evt);
            }
        });
        jPanel7.add(jchkb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jtxtb7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtb7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtb7.setText("0");
        jPanel7.add(jtxtb7, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 300, 70, 30));

        jtxtb1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtb1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtb1.setText("0");
        jPanel7.add(jtxtb1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 70, 30));

        jtxtb2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtb2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtb2.setText("0");
        jPanel7.add(jtxtb2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 70, 30));

        jtxtb3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtb3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtb3.setText("0");
        jPanel7.add(jtxtb3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 70, 30));

        jtxtb4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtb4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtb4.setText("0");
        jPanel7.add(jtxtb4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 70, 30));

        jtxtb5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtb5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtb5.setText("0");
        jtxtb5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtb5ActionPerformed(evt);
            }
        });
        jPanel7.add(jtxtb5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 70, 30));

        jtxtb6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jtxtb6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtb6.setText("0");
        jPanel7.add(jtxtb6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 70, 30));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 360));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Tax");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 50, -1));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Sub Total");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("Total Cost");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, -1, -1));

        jtxttotal.setBackground(new java.awt.Color(204, 204, 204));
        jtxttotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxttotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxttotal.setText("0");
        jPanel4.add(jtxttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, 100, -1));

        jtxttax.setBackground(new java.awt.Color(204, 204, 204));
        jtxttax.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxttax.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxttax.setText("0");
        jtxttax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxttaxActionPerformed(evt);
            }
        });
        jPanel4.add(jtxttax, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 390, 100, -1));

        jtxtsubtotal.setBackground(new java.awt.Color(204, 204, 204));
        jtxtsubtotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jtxtsubtotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtsubtotal.setText("0");
        jtxtsubtotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtsubtotalActionPerformed(evt);
            }
        });
        jPanel4.add(jtxtsubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 420, 100, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 360, 500));

        jPanel5.setBackground(new java.awt.Color(204, 204, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createMatteBorder(7, 7, 7, 7, new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtxtreceipt.setColumns(20);
        jtxtreceipt.setRows(5);
        jScrollPane1.setViewportView(jtxtreceipt);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 320, 340));

        jPanel8.setBackground(new java.awt.Color(204, 204, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createMatteBorder(5, 5, 5, 5, new java.awt.Color(0, 0, 0)));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton1.setText("Total");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 90, -1));

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton2.setText("Print");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jButton3.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 90, 40));

        jPanel5.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 320, 100));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 360, 500));

        jLabel5.setFont(new java.awt.Font("French Script MT", 2, 100)); // NOI18N
        jLabel5.setText("  Gaslight Cafe");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 520, 120));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1310, 830));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtcustomerrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcustomerrefActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcustomerrefActionPerformed

    private void jtxtfirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtfirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtfirstnameActionPerformed

    private void jtxtlastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtlastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtlastnameActionPerformed

    private void jchklblackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchklblackActionPerformed
         if(jchklblack.isSelected())
        {
            jtxtlblack.setEnabled(true);
            jtxtlblack.setText("");
            jtxtlblack.requestFocus();
        }
        else
        {
            jtxtlblack.setEnabled(false);
            jtxtlblack.setText("0");
        }
    }//GEN-LAST:event_jchklblackActionPerformed

    private void jchkb4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkb4ActionPerformed
        if(jchkb4.isSelected())
        {
            jtxtb4.setEnabled(true);
            jtxtb4.setText("");
            jtxtb4.requestFocus();
        }
        else
        {
            jtxtb4.setEnabled(false);
            jtxtb4.setText("0");
        }
    }//GEN-LAST:event_jchkb4ActionPerformed

    private void jchkb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkb1ActionPerformed
        if(jchkb1.isSelected())
        {
            jtxtb1.setEnabled(true);
            jtxtb1.setText("");
            jtxtb1.requestFocus();
        }
        else
        {
            jtxtb1.setEnabled(false);
            jtxtb1.setText("0");
        }
    }//GEN-LAST:event_jchkb1ActionPerformed

    private void jtxtespressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtespressoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtespressoActionPerformed

    private void jtxtcwcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtcwcActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtcwcActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jtxtespresso.setEnabled(false);
        jtxticedcoffee.setEnabled(false);
        jtxtmacchiato.setEnabled(false);
        jtxtcwc.setEnabled(false);
        jtxtcc.setEnabled(false);
        jtxtlblack.setEnabled(false);
        jtxthouseb.setEnabled(false);
        jtxtdecaf.setEnabled(false);
        jtxtlatte.setEnabled(false);
        jtxticedf.setEnabled(false);
        jtxtb1.setEnabled(false);
        jtxtb2.setEnabled(false);
        jtxtb3.setEnabled(false);
        jtxtb4.setEnabled(false);
        jtxtb5.setEnabled(false);
        jtxtb6.setEnabled(false);
        jtxtb7.setEnabled(false);
        
        jtxtespresso.setText("0");
        jtxticedcoffee.setText("0");
        jtxtmacchiato.setText("0");
        jtxtcwc.setText("0");
        jtxtcc.setText("0");
        jtxtlblack.setText("0");
        jtxthouseb.setText("0");
        jtxtdecaf.setText("0");
        jtxtlatte.setText("0");
        jtxticedf.setText("0");
        jtxtb1.setText("0");
        jtxtb2.setText("0");
        jtxtb3.setText("0");
        jtxtb4.setText("0");
        jtxtb5.setText("0");
        jtxtb6.setText("0");
        jtxtb7.setText("0");
        
        jchkespresso.setSelected(false);
        jchkicedcoffee.setSelected(false);
        jchkmacchiato.setSelected(false);
        jchkcwc.setSelected(false);
        jchkcc.setSelected(false);
        jchklblack.setSelected(false);
        jchkhouseb.setSelected(false);
        jchkdecaf.setSelected(false);
        jchklatte.setSelected(false);
        jchkicedf.setSelected(false);
        jchkb1.setSelected(false);
        jchkb2.setSelected(false);
        jchkb3.setSelected(false);
        jchkb4.setSelected(false);
        jchkb5.setSelected(false);
        jchkb6.setSelected(false);
        jchkb7.setSelected(false);
        
        jtxtcustomerref.setText(null);
        jtxtcustomerref.setEnabled(false);
        int ref = 145 + (int) (Math.random()*202);
        String cref = "";
        cref += ref+0;
        jtxtcustomerref.setText(cref);
        
        jtxtfirstname.setText(null);
        jtxtlastname.setText(null);
        jtxtmobileno.setText(null);
        jtxttax.setText(null);
        jtxtsubtotal.setText(null);
        jtxttotal.setText(null);
        
        jtxtreceipt.setText(null);
        
    }//GEN-LAST:event_jButton4ActionPerformed
private JFrame frame;
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         // TODO add your handling code here:
         frame = new JFrame("Exit");
         if (JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit", "Customer Billing System",
                 JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
             System.exit(0);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        jtxtespresso.setEnabled(false);
        jtxticedcoffee.setEnabled(false);
        jtxtmacchiato.setEnabled(false);
        jtxtcwc.setEnabled(false);
        jtxtcc.setEnabled(false);
        jtxtlblack.setEnabled(false);
        jtxthouseb.setEnabled(false);
        jtxtdecaf.setEnabled(false);
        jtxtlatte.setEnabled(false);
        jtxticedf.setEnabled(false);
        jtxtb1.setEnabled(false);
        jtxtb2.setEnabled(false);
        jtxtb3.setEnabled(false);
        jtxtb4.setEnabled(false);
        jtxtb5.setEnabled(false);
        jtxtb6.setEnabled(false);
        jtxtb7.setEnabled(false);
        
        jtxtcustomerref.setEnabled(false);
        int ref = 145 + (int) (Math.random()*202);
        String cref = "";
        cref += ref+0;
        
        
        jtxtcustomerref.setText(cref);
        jtxtfirstname.setText(null);
        jtxtlastname.setText(null);
        jtxtmobileno.setText(null);
        jtxttax.setText(null);
        jtxtsubtotal.setText(null);
        jtxttotal.setText(null);
        
        
        
        
        
        
       
    }//GEN-LAST:event_formWindowActivated

    private void jtxtb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtb5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtb5ActionPerformed

    private void jtxttaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxttaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxttaxActionPerformed

    private void jtxtsubtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtsubtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtsubtotalActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try
        {
            jtxtreceipt.print();
        }
        catch(java.awt.print.PrinterException e){
            System.err.format("No Printer found", e.getMessage());
        }
        
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jchkespressoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkespressoActionPerformed
        if(jchkespresso.isSelected())
        {
            jtxtespresso.setEnabled(true);
            jtxtespresso.setText("");
            jtxtespresso.requestFocus();
        }
        else
        {
            jtxtespresso.setEnabled(false);
            jtxtespresso.setText("0");
        }
    }//GEN-LAST:event_jchkespressoActionPerformed

    private void jchkicedcoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkicedcoffeeActionPerformed
         if(jchkicedcoffee.isSelected())
        {
            jtxticedcoffee.setEnabled(true);
            jtxticedcoffee.setText("");
            jtxticedcoffee.requestFocus();
        }
        else
        {
            jtxticedcoffee.setEnabled(false);
            jtxticedcoffee.setText("0");
        }

    }//GEN-LAST:event_jchkicedcoffeeActionPerformed

    private void jchkmacchiatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkmacchiatoActionPerformed
        if(jchkmacchiato.isSelected())
        {
            jtxtmacchiato.setEnabled(true);
            jtxtmacchiato.setText("");
            jtxtmacchiato.requestFocus();
        }
        else
        {
            jtxtmacchiato.setEnabled(false);
            jtxtmacchiato.setText("0");
        }
    }//GEN-LAST:event_jchkmacchiatoActionPerformed

    private void jchkcwcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkcwcActionPerformed
         if(jchkcwc.isSelected())
        {
            jtxtcwc.setEnabled(true);
            jtxtcwc.setText("");
            jtxtcwc.requestFocus();
        }
        else
        {
            jtxtcwc.setEnabled(false);
            jtxtcwc.setText("0");
        }
    }//GEN-LAST:event_jchkcwcActionPerformed

    private void jchkccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkccActionPerformed
         if(jchkcc.isSelected())
        {
            jtxtcc.setEnabled(true);
            jtxtcc.setText("");
            jtxtcc.requestFocus();
        }
        else
        {
            jtxtcc.setEnabled(false);
            jtxtcc.setText("0");
        }
    }//GEN-LAST:event_jchkccActionPerformed

    private void jchkhousebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkhousebActionPerformed
         if(jchkhouseb.isSelected())
        {
            jtxthouseb.setEnabled(true);
            jtxthouseb.setText("");
            jtxthouseb.requestFocus();
        }
        else
        {
            jtxthouseb.setEnabled(false);
            jtxthouseb.setText("0");
        }
    }//GEN-LAST:event_jchkhousebActionPerformed

    private void jchkdecafActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkdecafActionPerformed
        if(jchkdecaf.isSelected())
        {
            jtxtdecaf.setEnabled(true);
            jtxtdecaf.setText("");
            jtxtdecaf.requestFocus();
        }
        else
        {
            jtxtdecaf.setEnabled(false);
            jtxtdecaf.setText("0");
        }
    }//GEN-LAST:event_jchkdecafActionPerformed

    private void jchklatteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchklatteActionPerformed
        if(jchklatte.isSelected())
        {
            jtxtlatte.setEnabled(true);
            jtxtlatte.setText("");
            jtxtlatte.requestFocus();
        }
        else
        {
            jtxtlatte.setEnabled(false);
            jtxtlatte.setText("0");
        }
    }//GEN-LAST:event_jchklatteActionPerformed

    private void jchkicedfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkicedfActionPerformed
        if(jchkicedf.isSelected())
        {
            jtxticedf.setEnabled(true);
            jtxticedf.setText("");
            jtxticedf.requestFocus();
        }
        else
        {
            jtxticedf.setEnabled(false);
            jtxticedf.setText("0");
        }
    }//GEN-LAST:event_jchkicedfActionPerformed

    private void jchkb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkb2ActionPerformed
        if(jchkb2.isSelected())
        {
            jtxtb2.setEnabled(true);
            jtxtb2.setText("");
            jtxtb2.requestFocus();
        }
        else
        {
            jtxtb2.setEnabled(false);
            jtxtb2.setText("0");
        }
    }//GEN-LAST:event_jchkb2ActionPerformed

    private void jchkb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkb3ActionPerformed
        if(jchkb3.isSelected())
        {
            jtxtb3.setEnabled(true);
            jtxtb3.setText("");
            jtxtb3.requestFocus();
        }
        else
        {
            jtxtb3.setEnabled(false);
            jtxtb3.setText("0");
        }
    }//GEN-LAST:event_jchkb3ActionPerformed

    private void jchkb5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkb5ActionPerformed
        if(jchkb5.isSelected())
        {
            jtxtb5.setEnabled(true);
            jtxtb5.setText("");
            jtxtb5.requestFocus();
        }
        else
        {
            jtxtb5.setEnabled(false);
            jtxtb5.setText("0");
        }
    }//GEN-LAST:event_jchkb5ActionPerformed

    private void jchkb6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkb6ActionPerformed
        if(jchkb6.isSelected())
        {
            jtxtb6.setEnabled(true);
            jtxtb6.setText("");
            jtxtb6.requestFocus();
        }
        else
        {
            jtxtb6.setEnabled(false);
            jtxtb6.setText("0");
        }
    }//GEN-LAST:event_jchkb6ActionPerformed

    private void jchkb7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jchkb7ActionPerformed
        if(jchkb7.isSelected())
        {
            jtxtb7.setEnabled(true);
            jtxtb7.setText("");
            jtxtb7.requestFocus();
        }
        else
        {
            jtxtb7.setEnabled(false);
            jtxtb7.setText("0");
        }
    }//GEN-LAST:event_jchkb7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        itemcost[0]= Double.parseDouble(jtxtespresso.getText())*5.90;
        itemcost[1]= Double.parseDouble(jtxticedcoffee.getText())*4.95;
        itemcost[2]= Double.parseDouble(jtxtmacchiato.getText())*5.95;
        itemcost[3]= Double.parseDouble(jtxtcwc.getText())*5.95;
        itemcost[4]= Double.parseDouble(jtxtcc.getText())*4.25;
        itemcost[5]= Double.parseDouble(jtxtlblack.getText())*2.99;
        itemcost[6]= Double.parseDouble(jtxthouseb.getText())*2.99;
        itemcost[7]= Double.parseDouble(jtxtdecaf.getText())*2.99;
        itemcost[8]= Double.parseDouble(jtxtlatte.getText())*4.95;
        itemcost[9]= Double.parseDouble(jtxticedf.getText())*3.00;
        itemcost[10]= Double.parseDouble(jtxtb1.getText())*13;
        itemcost[11]= Double.parseDouble(jtxtb2.getText())*12.99;
        itemcost[12]= Double.parseDouble(jtxtb3.getText())*15.99;
        itemcost[13]= Double.parseDouble(jtxtb4.getText())*10.45;
        itemcost[14]= Double.parseDouble(jtxtb5.getText())*11.99;
        itemcost[15]= Double.parseDouble(jtxtb6.getText())*20;
        itemcost[16]= Double.parseDouble(jtxtb7.getText())*8.99;
        
        itemcost[17]=itemcost[0]+itemcost[1]+itemcost[2]+itemcost[3]+itemcost[4]+itemcost[5]+itemcost[6]+itemcost[7]+itemcost[8]+itemcost[9];
        itemcost[18]=itemcost[10]+itemcost[11]+itemcost[12]+itemcost[13]+itemcost[14]+itemcost[15]+itemcost[16];
        
        itemcost[19]=itemcost[17]+itemcost[18];
        
        iTax = String.format("$ %.2f" , (itemcost[19]*12)/100);
        iSubTotal = String.format("$ %.2f" , itemcost[19]);
        iTotal = String.format("$ %.2f" , itemcost[19] + ((itemcost[19]*12)/100));
        
        jtxttax.setText(iTax);
        jtxtsubtotal.setText(iSubTotal);
        jtxttotal.setText(iTotal);
        
        //-------------------------------------------------------------------------------------
        jtxtreceipt.setEnabled(true);
        //-------------------------------------------------------------------------------------
        int ref = 145 + (int) (Math.random()*202);
        
        Calendar timer = Calendar.getInstance();
        timer.getTime();
        SimpleDateFormat tTime = new SimpleDateFormat("HH:mm:ss");
        tTime.format(timer.getTime());
        SimpleDateFormat tDate = new SimpleDateFormat("dd-mm-yyyy");
        tDate.format(timer.getTime());
        
        jtxtreceipt.append("\t   Gaslight Cafe\n" +
                "Reference:\t\t\t" + ref +
                "\n=========================================\t" +
                
                     "\n=========================================\t" +
                     "\nFirstname:\t\t\t" + jtxtfirstname.getText() +
                     "\nLastname:\t\t\t" + jtxtlastname.getText() 
                );
        if(jchkespresso.isSelected()){
            jtxtreceipt.append("\nEspresso:\t\t\t" + jtxtespresso.getText());
          }
        if(jchkicedcoffee.isSelected()){
            jtxtreceipt.append("\nIced Coffee:\t\t\t" + jtxticedcoffee.getText());
          }
        if(jchkmacchiato.isSelected()){
            jtxtreceipt.append("\nMacchiato:\t\t\t" + jtxtmacchiato.getText());
          }
        if(jchkcwc.isSelected()){
            jtxtreceipt.append("\nCoffee with Cream:\t\t" + jtxtcwc.getText());
          }
        if(jchkcc.isSelected()){
            jtxtreceipt.append("\nChocolate Coffee:\t\t" + jtxtcc.getText());
          }
        if(jchklblack.isSelected()){
            jtxtreceipt.append("\nLong Black:\t\t\t" + jtxtlblack.getText());
          }
        if(jchkhouseb.isSelected()){
            jtxtreceipt.append("\nHouse Blend:\t\t\t" + jtxthouseb.getText());
          }
        if(jchklatte.isSelected()){
            jtxtreceipt.append("\nLatte:\t\t\t" + jtxtlatte.getText());
          }
        if(jchkdecaf.isSelected()){
            jtxtreceipt.append("\nDecaf Coffee:\t\t\t" + jtxtdecaf.getText());
          }
        if(jchkicedf.isSelected()){
            jtxtreceipt.append("\nIced Frappe:\t\t\t" + jtxticedf.getText());
          }
        if(jchkb1.isSelected()){
            jtxtreceipt.append("\nSpanish Omelette:\t\t" + jtxtb1.getText());
          }
        if(jchkb2.isSelected()){
            jtxtreceipt.append("\nEggs Benedict:\t\t\t" + jtxtb2.getText());
          }
        if(jchkb3.isSelected()){
            jtxtreceipt.append("\nNutella French Toast:\t\t" + jtxtb3.getText());
          }
        if(jchkb4.isSelected()){
            jtxtreceipt.append("\nS'mores Crepes:\t\t" + jtxtb4.getText());
          }
        if(jchkb5.isSelected()){
            jtxtreceipt.append("\nWaffle Attack:\t\t\t" + jtxtb5.getText());
          }
        if(jchkb6.isSelected()){
            jtxtreceipt.append("\nEnglish Breakfast:\t\t" + jtxtb6.getText());
          }
        if(jchkb7.isSelected()){
            jtxtreceipt.append("\nGranola + Yogurt:\t\t" + jtxtb7.getText());
          }
        
               
                jtxtreceipt.append(
                     "\nTax:\t\t\t" + iTax +
                     "\nSub Total:\t\t\t" + iSubTotal +
                     "\nTotal:\t\t\t" + iTotal +
                     "\n=========================================\t" +
                     "\nDate: " + tDate.format(timer.getTime()) +
                       "\t\tTime: " + tTime.format(timer.getTime()) +
                "\n\n\t Thank you! Visit again.\n"
                
    );    
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Customer_billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Customer_billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Customer_billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Customer_billing.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Customer_billing().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JCheckBox jchkb1;
    private javax.swing.JCheckBox jchkb2;
    private javax.swing.JCheckBox jchkb3;
    private javax.swing.JCheckBox jchkb4;
    private javax.swing.JCheckBox jchkb5;
    private javax.swing.JCheckBox jchkb6;
    private javax.swing.JCheckBox jchkb7;
    private javax.swing.JCheckBox jchkcc;
    private javax.swing.JCheckBox jchkcwc;
    private javax.swing.JCheckBox jchkdecaf;
    private javax.swing.JCheckBox jchkespresso;
    private javax.swing.JCheckBox jchkhouseb;
    private javax.swing.JCheckBox jchkicedcoffee;
    private javax.swing.JCheckBox jchkicedf;
    private javax.swing.JCheckBox jchklatte;
    private javax.swing.JCheckBox jchklblack;
    private javax.swing.JCheckBox jchkmacchiato;
    private javax.swing.JTextField jtxtb1;
    private javax.swing.JTextField jtxtb2;
    private javax.swing.JTextField jtxtb3;
    private javax.swing.JTextField jtxtb4;
    private javax.swing.JTextField jtxtb5;
    private javax.swing.JTextField jtxtb6;
    private javax.swing.JTextField jtxtb7;
    private javax.swing.JTextField jtxtcc;
    private javax.swing.JTextField jtxtcustomerref;
    private javax.swing.JTextField jtxtcwc;
    private javax.swing.JTextField jtxtdecaf;
    private javax.swing.JTextField jtxtespresso;
    private javax.swing.JTextField jtxtfirstname;
    private javax.swing.JTextField jtxthouseb;
    private javax.swing.JTextField jtxticedcoffee;
    private javax.swing.JTextField jtxticedf;
    private javax.swing.JTextField jtxtlastname;
    private javax.swing.JTextField jtxtlatte;
    private javax.swing.JTextField jtxtlblack;
    private javax.swing.JTextField jtxtmacchiato;
    private javax.swing.JTextField jtxtmobileno;
    private javax.swing.JTextArea jtxtreceipt;
    private javax.swing.JTextField jtxtsubtotal;
    private javax.swing.JTextField jtxttax;
    private javax.swing.JTextField jtxttotal;
    // End of variables declaration//GEN-END:variables
}

